[package]
name = "aio-bindings"
version = "0.1.0"
authors = ["Hans-Martin Will <hwill@acm.org>"]
description = "Native kernel call bindings for Linux AIO"
repository="https://github.com/hmwill/tokio-linux-aio/aio-bindings"
license = "MIT"

[dependencies]

[build-dependencies]
bindgen = "0.32.3"